import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Authenticate from "@/containers/Authenticate/authenticate";
import Header from "@/components/header";
import FloatingActionButton from "@/components/floation-action-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Authenticate> <Header/>{children}
      {/* <FloatingActionButton /> */}
        
        </Authenticate>
      </body>
    </html>
  );
}
